### ISSUE TITLE
TypeError on reviewer approval (v2.0.0)

### ISSUE THREAD

**Issue by green17** [engram-design/Workflow#166]
### Describe the bug

Recently we upgraded from 2.0.0-beta-6 to 2.0.0. We have a three step process setup: an editor, a reviewer, and a publisher. Because we required a specific user to function as the reviewer for a given entry (and this user can be different for each entry) we added in some custom logic into our plugin using the EVENT_BEFORE_SEND_REVIEWER_EMAIL event. This worked great in 2.0.0.-beta-6. We have recently upgraded to 2.0.0 and made the recommended code changes but when we tested the workflow, upon approving as a reviewer we ended up getting a type error. In terms of the workflow itself, the dashboard showed the approval having gone through. The error seems to be in generating the email.

We have also experimented with removing our custom plugin code entirely but ran into the same issue.

Please see below for the error that was generated.

**TypeError**
verbb\workflow\services\Emails::sendPublisherNotificationEmail(): Argument #2 ($review) must be of type verbb\workflow\models\Review, craft\elements\Entry given, called in /var/www/html/vendor/verbb/workflow/src/services/Emails.php on line 51

### Steps to reproduce

```
use verbb\workflow\events\EmailEvent;
use verbb\workflow\events\PrepareEmailEvent;
use verbb\workflow\services\Emails;

// Custom plugin snippet
Event::on(Emails::class, Emails::EVENT_BEFORE_SEND_REVIEWER_EMAIL, function(EmailEvent $event) {
    $mail = $event->mail;
    $user = $event->user;
    $reviewers = $event->reviewers;
    $submission = $event->submission;

   // Custom code

}
```

### Craft CMS version

4.2.5.1

### Plugin version

2.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-4 as 2.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by green17** [comment]
Thanks @engram-design, much appreciated!

**Comment by green17** [comment]
Hi @engram-design, I have installed Workflow via the steps above but encountered an error when trying to submit a draft for approval. Upon clicking on the "Save draft and submit for review" button I'm directed to an error page ("Undefined variable $site"). I've updated our custom plugin as recommended for upgrading from v1 and tested without our plugin but still get the error.

**Comment by engram-design** [comment]
@green17 Are you able to provide the full stack trace of the error? I can't seem to track down exactly where that might be coming from.

**Comment by green17** [comment]
Hi @engram-design, please see stack trace below:

```
yii\base\ErrorException: Undefined variable $site in /var/www/html/vendor/verbb/workflow/src/services/Submissions.php:411
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined varia...', '/var/www/html/v...', 411)
#1 /var/www/html/vendor/verbb/workflow/src/services/Submissions.php(411): craft\web\ErrorHandler->handleError(2, 'Undefined varia...', '/var/www/html/v...', 411)
#2 /var/www/html/vendor/verbb/workflow/src/services/Submissions.php(98): verbb\workflow\services\Submissions->_setSubmissionFromPost()
#3 /var/www/html/vendor/verbb/workflow/src/services/Service.php(139): verbb\workflow\services\Submissions->saveSubmission(Object(craft\elements\Entry))
#4 [internal function]: verbb\workflow\services\Service->onAfterSaveElement(Object(craft\events\ElementEvent))
#5 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\ElementEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2879): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#8 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1262): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), false, false, true, Array)
#9 /var/www/html/vendor/craftcms/cms/src/services/Revisions.php(162): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#10 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1995): craft\services\Revisions->createRevision(Object(craft\elements\Entry), 2849, '')
#11 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2777): craft\elements\Entry->afterPropagate(false)
#12 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(795): craft\services\Elements->_saveElementInternal(Object(craft\elements\Entry), true, false, true)
#13 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(882): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#14 [internal function]: craft\controllers\ElementsController->actionSave()
#15 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#17 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#18 /var/www/html/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('elements/save', Array)
#19 /var/www/html/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('elements/save', Array)
#20 /var/www/html/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#21 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /var/www/html/web/index.php(12): yii\base\Application->run()
#23 {main}
```

**Comment by engram-design** [comment]
Thanks for that! Fixed in [2.0.1](https://github.com/verbb/workflow/releases/tag/2.0.1)
