### ISSUE TITLE
Diacritics (umlauts) are incorrectly escaped in some cases

### ISSUE THREAD

**Issue by MoritzLost** [engram-design/Workflow#182]
### Describe the bug

If editor or publisher notes include diacritics (e.g. Ä Ö Ü, very common in German), they are double escaped or incorrectly escaped in some cases. In the workflow overview and the submission detail views, the text is escaped twice:

![workflow-overview](https://user-images.githubusercontent.com/10146880/214857574-e8b0e52a-095b-4cd1-b79d-15baca74eefd.png)

![submission-details-view](https://user-images.githubusercontent.com/10146880/214857619-28a9a1dc-383c-4e8b-97b2-3aa9af8a3ffa.png)

In the editor view at the right side of the entry edit form, the text is also escaped twice:

![entry-editor-view](https://user-images.githubusercontent.com/10146880/214858456-53ef65b0-fe52-4a29-82d2-1585761279c5.png)

In the confirmation email, diacritics are correctly escaped once and displayed normally:

![Screenshot 2023-01-26 at 15 02 50](https://user-images.githubusercontent.com/10146880/214858534-b8f72eb0-9ba0-42fe-9dc0-aeffafae7156.png)

However, in the text version of the email, diacritics are also escaped – but HTML entities don't work here since it's plain text, so the diacritics shouldn't be escaped at all:

![Screenshot 2023-01-26 at 15 02 55](https://user-images.githubusercontent.com/10146880/214858824-9dc5a278-89a1-43c9-846a-3eb835834bf1.png)

### Steps to reproduce

1. Enter text with diacritics/umlauts in the notes field as an editor or publisher, for example `Notes with Ä Ö Ümlauts`
2. Check the notes in the different places they appear in the interface, and check the confirmation emails.

### Craft CMS version

4.3.6.1

### Plugin version

2.0.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-4 as 2.0.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by MoritzLost** [comment]
@engram-design Thanks! Just tried the new version, I can confirm that it fixes the issue in the submission details view, the editor/publisher panel on the entry edit page and the notification emails. But I'm still seeing the same issue in the workflow list (the element index):

![Screenshot 2023-01-27 at 10 12 00](https://user-images.githubusercontent.com/10146880/215049891-0d96707e-96e2-41b1-8197-b926cb0e6436.png)

Can you take another look? Thanks!

**Comment by engram-design** [comment]
Whoops, forgot that! Just updated.

**Comment by MoritzLost** [comment]
@engram-design Works perfectly, thanks!

**Comment by engram-design** [comment]
Fixed in [2.0.4](https://github.com/verbb/workflow/releases/tag/2.0.4)
